# Generated by Django 3.0.3 on 2020-10-31 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaInforme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificacion', models.CharField(blank=True, max_length=400)),
                ('estado', models.CharField(default=None, max_length=100, null=True)),
                ('creador', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creadorActa', to=settings.AUTH_USER_MODEL)),
                ('gerente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='gerenteActa', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectoActa', to='proyecto.Proyecto')),
            ],
        ),
    ]
