# Generated by Django 3.0.3 on 2020-10-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roturalineabase',
            name='estado_solicitud',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
