# Generated by Django 3.0.3 on 2020-04-13 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='fases',
        ),
    ]
