# Generated by Django 3.0.3 on 2020-08-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem',
            name='dateCreacion',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='dateCreacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
