# Generated by Django 3.0.3 on 2020-08-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fase',
            name='tipoItem',
            field=models.ManyToManyField(default=None, to='proyecto.TipodeItem'),
        ),
    ]
