# Generated by Django 3.0.3 on 2020-09-14 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalitem',
            name='version',
        ),
    ]
