# Generated by Django 3.0.3 on 2020-11-01 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_auto_20201101_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='acta',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acta_informe', to='proyecto.ActaInforme'),
        ),
    ]
