# Generated by Django 3.0.3 on 2020-10-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_roturalineabase_estado_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='roturalineabase',
            name='fecha',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
