# Generated by Django 3.0.3 on 2020-09-14 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_remove_historicalitem_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem',
            name='version',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
