# Generated by Django 3.0.3 on 2020-04-13 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_remove_proyecto_fases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faseuser',
            name='fase',
        ),
    ]
