# Generated by Django 3.0.3 on 2020-10-31 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_actainforme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actainforme',
            name='creador',
        ),
        migrations.RemoveField(
            model_name='actainforme',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='actainforme',
            name='gerente',
        ),
        migrations.RemoveField(
            model_name='actainforme',
            name='proyecto',
        ),
        migrations.AddField(
            model_name='actainforme',
            name='fecha_fin',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='acta',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='acta', to='proyecto.ActaInforme'),
        ),
    ]
