# Generated by Django 3.0.3 on 2020-09-16 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_auto_20200916_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='archivos',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='proyecto.Files'),
        ),
    ]
