# Generated by Django 3.0.3 on 2020-09-17 12:32

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_historicalrelacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='proyecto.Item'),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='archivos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, size=None),
        ),
        migrations.RemoveField(
            model_name='item',
            name='archivos',
        ),
        migrations.AddField(
            model_name='item',
            name='archivos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, size=None),
        ),
    ]
