# Generated by Django 3.0.3 on 2020-11-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_auto_20201101_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='acta',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='acta',
            field=models.ManyToManyField(blank=True, default=None, related_name='acta_informe', to='proyecto.ActaInforme'),
        ),
    ]
