# Generated by Django 3.0.3 on 2020-10-03 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_roturalineabase_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roturalineabase',
            name='estado_solicitud',
        ),
    ]
