# Generated by Django 3.0.3 on 2020-08-24 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_auto_20200824_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='relaciones',
        ),
    ]
