# Generated by Django 3.0.3 on 2020-10-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_auto_20201011_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fase',
            name='descripcion',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='nombre',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='observacion',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='tipodeitem',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
    ]
