# Generated by Django 3.0.3 on 2020-09-17 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_auto_20200917_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterModelOptions(
            name='fase',
            options={'permissions': (('create_item', 'Can create item'), ('aprove_item', 'Can aprove item'), ('modify_item', 'Can modify item'), ('unable_item', 'Can unable item'), ('reversionar_item', 'Reversionar item'), ('relacionar_item', 'Relacionar item'), ('change_item', 'Can change item'), ('establecer_itemPendienteAprob', 'Establecer ítem como pendiente de aprobación.'), ('establecer_itemDesarrollo', 'Establecer ítem como en desarrollo.'), ('obtener_trazabilidadItem', 'Obtener trazabilidad de ítem.'), ('ver_item', 'Visualizar ítem.'), ('deshabilitar_item', 'Deshabilitar Item'), ('obtener_calculoImpacto', 'Obtener cálculo de impacto de ítem.'), ('create_lineaBase', 'Crear Línea Base.'), ('modify_lineaBase', 'Modificar Linea Base.'), ('ver_lineaBase', 'Ver Línea Base.'), ('break_lineaBase', 'Romper Línea Base.'), ('solicitar_roturaLineaBase', 'Solicitar rotura de línea base.'), ('cerrar_fase', 'cerrar fase'))},
        ),
        migrations.CreateModel(
            name='CampoExtraValores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=40)),
                ('campoExtra', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='campoExtra', to='proyecto.CampoExtra')),
            ],
        ),
    ]
