# Generated by Django 3.0.3 on 2020-10-31 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_auto_20201031_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='acta',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acta', to='proyecto.ActaInforme'),
        ),
    ]
