# Generated by Django 3.0.3 on 2020-09-16 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_auto_20200916_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalitem',
            name='archivos',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proyecto.Files'),
        ),
        migrations.AlterField(
            model_name='item',
            name='archivos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='proyecto.Files'),
        ),
    ]
