# Generated by Django 3.0.3 on 2020-04-13 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_remove_faseuser_fase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectofase',
            name='fase',
        ),
    ]
