# Generated by Django 3.0.3 on 2020-09-17 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_auto_20200917_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalfaseuser',
            name='fase',
        ),
        migrations.RemoveField(
            model_name='historicalfaseuser',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalfaseuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicalproyecto',
            name='creador',
        ),
        migrations.RemoveField(
            model_name='historicalproyecto',
            name='gerente',
        ),
        migrations.RemoveField(
            model_name='historicalproyecto',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalproyectofase',
            name='fase',
        ),
        migrations.RemoveField(
            model_name='historicalproyectofase',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalproyectofase',
            name='proyecto',
        ),
        migrations.DeleteModel(
            name='HistoricalFase',
        ),
        migrations.DeleteModel(
            name='HistoricalFaseUser',
        ),
        migrations.DeleteModel(
            name='HistoricalProyecto',
        ),
        migrations.DeleteModel(
            name='HistoricalProyectoFase',
        ),
    ]
