# Generated by Django 3.0.3 on 2020-04-13 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_remove_proyectofase_fase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fase',
        ),
    ]
