# Generated by Django 3.0.3 on 2020-09-16 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_auto_20200916_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='archivos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='proyecto.Files'),
        ),
    ]
