# Generated by Django 3.0.3 on 2020-10-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_auto_20201031_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actainforme',
            name='fecha_fin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='actainforme',
            name='justificacion',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
