# Generated by Django 3.0.3 on 2020-08-24 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_remove_item_relaciones'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Relacion',
            new_name='Relacionn',
        ),
    ]
