# Generated by Django 3.0.3 on 2020-10-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_remove_roturalineabase_estado_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='roturalineabase',
            name='estado',
            field=models.CharField(default='pendiente', max_length=40),
        ),
    ]
