# Generated by Django 3.0.3 on 2020-10-05 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyecto', '0005_roturalineabase_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoturaLineaBaseComprometida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uno_voto_comprometida', models.SmallIntegerField(default=-1)),
                ('dos_voto_comprometida', models.SmallIntegerField(default=-1)),
                ('tres_voto_comprometida', models.SmallIntegerField(default=-1)),
                ('comprometida_estado', models.CharField(default='pendiente', max_length=40)),
                ('registrados_votos_comprometida', models.ManyToManyField(default=None, related_name='comprometidavotantes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lineabase',
            name='roturaLineaBaseComprometida',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comprometida', to='proyecto.RoturaLineaBaseComprometida'),
        ),
    ]
