# Generated by Django 3.0.3 on 2020-09-18 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_auto_20200917_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrol',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalrol',
            name='perms',
        ),
        migrations.RemoveField(
            model_name='historicalitem',
            name='dateCreacion',
        ),
        migrations.RemoveField(
            model_name='item',
            name='dateCreacion',
        ),
        migrations.DeleteModel(
            name='HistoricalRelacion',
        ),
        migrations.DeleteModel(
            name='HistoricalRol',
        ),
    ]
