# Generated by Django 3.0.3 on 2020-09-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_auto_20200916_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalitem',
            name='archivos',
        ),
        migrations.RemoveField(
            model_name='item',
            name='archivos',
        ),
        migrations.AddField(
            model_name='item',
            name='archivos',
            field=models.ManyToManyField(default=None, to='proyecto.Files'),
        ),
    ]
