# Generated by Django 3.0.3 on 2020-08-24 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_auto_20200824_1346'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Relacionn',
            new_name='Relacion',
        ),
    ]
