# Generated by Django 3.0.3 on 2020-10-31 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_auto_20201031_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actainforme',
            old_name='fecha_fin',
            new_name='fechafin',
        ),
    ]
