# Generated by Django 3.0.3 on 2020-09-16 23:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_auto_20200916_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem',
            name='campo_extra_valores',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, size=None),
        ),
    ]
