# Generated by Django 3.0.3 on 2020-10-05 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_auto_20201005_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineabase',
            name='roturaLineaBaseComprometida',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comprometida', to='proyecto.RoturaLineaBaseComprometida'),
        ),
    ]
