# Generated by Django 3.0.3 on 2020-10-04 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_auto_20200918_0126'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalItem',
        ),
    ]
