# Generated by Django 3.0.3 on 2020-08-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_auto_20200824_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='relaciones',
            field=models.ManyToManyField(default=None, through='proyecto.Relacion', to='proyecto.Item'),
        ),
    ]
