# Generated by Django 3.0.3 on 2020-04-14 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_auto_20200413_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='file',
        ),
    ]
