# Generated by Django 3.0.3 on 2020-10-31 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_auto_20201031_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='acta',
        ),
        migrations.DeleteModel(
            name='ActaInforme',
        ),
    ]
