# Generated by Django 3.0.3 on 2020-10-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0007_auto_20201005_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineabase',
            name='roturaslineasBase',
            field=models.ManyToManyField(blank=True, default=None, to='proyecto.RoturaLineaBase'),
        ),
    ]
