# Generated by Django 3.0.3 on 2020-08-24 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0007_item_relaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacion',
            name='fase_item_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='proyecto.Fase'),
        ),
    ]
