# Generated by Django 3.0.3 on 2020-10-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0008_auto_20201005_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineabase',
            name='roturaLineaBaseComprometida',
        ),
        migrations.AddField(
            model_name='lineabase',
            name='roturaLineaBaseComprometida',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='comprometida', to='proyecto.RoturaLineaBaseComprometida'),
        ),
    ]
