# Generated by Django 3.0.3 on 2020-08-25 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyecto', '0008_relacion_fase_item_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fase',
            options={'permissions': (('create_item', 'Can create item'), ('aprove_item', 'Can aprove item'), ('modify_item', 'Can modify item'), ('unable_item', 'Can unable item'), ('reversionar_item', 'Reversionar item'), ('relacionar_item', 'Relacionar item'), ('change_item', 'Can change item'), ('establecer_itemPendienteAprob', 'Establecer ítem como pendiente de aprobación.'), ('establecer_itemDesarrollo', 'Establecer ítem como en desarrollo.'), ('obtener_trazabilidadItem', 'Obtener trazabilidad de ítem.'), ('ver_item', 'Visualizar ítem.'), ('deshabilitar_item', 'Deshabilitar Item'), ('obtener_calculoImpacto', 'Obtener cálculo de impacto de ítem.'), ('create_lineaBase', 'Crear Línea Base.'), ('modify_lineaBase', 'Modificar Linea Base.'), ('ver_lineaBase', 'Ver Línea Base.'), ('break_lineaBase', 'Romper Línea Base.'), ('solicitar_roturaLineaBase', 'Solicitar rotura de línea base.'))},
        ),
        migrations.CreateModel(
            name='LineaBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=None, max_length=40)),
                ('estado', models.CharField(default=None, max_length=40)),
                ('creador', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(default=None, to='proyecto.Item')),
            ],
        ),
        migrations.AddField(
            model_name='fase',
            name='lineasBase',
            field=models.ManyToManyField(default=None, to='proyecto.LineaBase'),
        ),
    ]
