# Generated by Django 3.0.3 on 2020-04-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0008_auto_20200414_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='idTipo',
            field=models.IntegerField(default=None),
        ),
    ]
