# Generated by Django 3.0.3 on 2020-04-18 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0009_item_idtipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='idTipo',
        ),
    ]
