# Generated by Django 3.0.3 on 2020-10-05 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0009_auto_20201005_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineabase',
            name='roturaLineaBaseComprometida',
            field=models.ManyToManyField(blank=True, default=None, related_name='comprometida', to='proyecto.RoturaLineaBaseComprometida'),
        ),
    ]
