# Generated by Django 3.0.3 on 2020-04-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0010_remove_item_idtipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='idTipo',
            field=models.IntegerField(default=None),
        ),
    ]
