# Generated by Django 3.0.3 on 2020-10-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0010_auto_20201005_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem',
            name='faseid',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='item',
            name='faseid',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
