# Generated by Django 3.0.3 on 2020-04-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0011_item_idtipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='idTipo',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
