# Generated by Django 3.0.3 on 2020-04-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0012_auto_20200418_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='idTipo',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
