# Generated by Django 3.0.3 on 2020-04-18 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0013_auto_20200418_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='idTipo',
        ),
    ]
