# Generated by Django 3.0.3 on 2020-04-19 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0014_remove_item_idtipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fase',
            name='items',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
