# Generated by Django 3.0.3 on 2020-04-19 00:06

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0015_auto_20200419_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=None, max_length=40)),
                ('campo_extra_valores', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, size=None)),
                ('fecha', models.CharField(default=None, max_length=40)),
                ('estado', models.CharField(blank=True, max_length=40, null=True)),
                ('observacion', models.CharField(blank=True, default=None, max_length=50)),
                ('costo', models.IntegerField(blank=True, default=0)),
                ('tipoItem', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tipoItem', to='proyecto.TipodeItem')),
            ],
        ),
        migrations.AddField(
            model_name='fase',
            name='items',
            field=models.ManyToManyField(default=None, to='proyecto.Item'),
        ),
    ]
