# Generated by Django 3.0.3 on 2020-04-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0016_auto_20200419_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
