# Generated by Django 3.0.3 on 2020-04-25 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0018_auto_20200424_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default=None, max_length=40)),
                ('item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='proyecto.Item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='relaciones',
            field=models.ManyToManyField(default=None, related_name='_item_relaciones_+', through='proyecto.Relacion', to='proyecto.Item'),
        ),
    ]
