# Generated by Django 3.0.3 on 2020-04-25 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0019_auto_20200425_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relacion',
            name='item',
        ),
        migrations.AddField(
            model_name='relacion',
            name='item_from',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='item_from', to='proyecto.Item'),
        ),
        migrations.AddField(
            model_name='relacion',
            name='item_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='item_to', to='proyecto.Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='relaciones',
            field=models.ManyToManyField(default=None, through='proyecto.Relacion', to='proyecto.Item'),
        ),
    ]
