# Generated by Django 3.0.3 on 2020-04-26 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0020_auto_20200425_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='relaciones',
        ),
        migrations.DeleteModel(
            name='Relacion',
        ),
    ]
