# Generated by Django 3.0.3 on 2020-04-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fase',
            name='descripcion',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
