# Generated by Django 3.0.3 on 2020-04-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fase', '0002_fase_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='fase',
            name='estado',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
