# Generated by Django 3.0.3 on 2020-04-13 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fase', '0003_fase_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='tipodeitem_ptr',
        ),
        migrations.DeleteModel(
            name='Fase',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
