# Generated by Django 3.0.3 on 2020-04-16 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fase', '0007_fase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fase',
        ),
    ]
